### PR TITLE
Improve HT32F165x support

### PR DESCRIPTION
**Pull request by jakllsch**
Mostly just doing this pull request to let everyone know this exists.  I've got an [example keyboard](https://github.com/jakllsch/tmk_microterm_esk32-300sk) using this too.

### CODE REVIEW

**Comment by ChaoticEnigma** [comment]
Wow, this is a lot. I've been going through this slowly. Man, those bitfields took forever.

**Comment by jakllsch** [comment]
Yeah, it is a lot.  I'd have liked to kept the bitfields, but between them being layout-defined-by-ABI, the potential register read side-effects, extra instructions generated for access, and not seeing any existing usage of them in ChibiOS for register access, I just couldn't bring myself to keep them.

I'm typing this on a Yoda II running QMK w/ a slightly refined version of the code in this pull request.  I'll work on getting it all pushed out tomorrow.

**Comment by ChaoticEnigma** [comment]
Wow, that's awesome. You've probably done more work on the ChibiOS stuff than I have. Definitely push what you've got. It looks like you've done the hard part, I'll work on porting it to the Vortex keyboards.

You're probably right about the bitfields. I never had any problems with them, but it was waiting to happen. I held on because they clear up bit-fiddling boilerplate quite a bit.

**Comment by ChaoticEnigma** [comment]
If your Yoda II is running QMK, is that on a local branch of your qmk_firmware repository? I'd be very interested to see what you've done there.

**Comment by jakllsch** [comment]
https://github.com/jakllsch/qmk_firmware/tree/ht32 under keyboards/yoda_ii

**Comment by ChaoticEnigma** [comment]
Sweet! But, `TEX_YODA_II/board.mk` is looking for `magic.S`, is that still needed? Replaced by `bootloader_magic` in `board.c`?

**Comment by jakllsch** [comment]
Yeah, replaced by bootloader_magic in board.c.  I never got it to actually compile the .S

**Pull request merged**
